import { useMemo, useState } from 'react'
import { Boxes, Cpu, Layers3, MemoryStick, Search, Server, ShieldCheck } from 'lucide-react'
import Badge from '../components/common/Badge.jsx'
import Card from '../components/common/Card.jsx'
import EmptyState from '../components/common/EmptyState.jsx'
import Modal from '../components/common/Modal.jsx'
import { SAMPLE_CLUSTER } from '../data/kubernetes.js'

const tabs = ['Overview', 'Nodes', 'Pods', 'Namespaces']
const podTone = { Running: 'success', Pending: 'orange', Failed: 'danger' }

function KubernetesPage() {
  const [tab, setTab] = useState('Overview')
  const [search, setSearch] = useState('')
  const [namespace, setNamespace] = useState('All namespaces')
  const [selected, setSelected] = useState(null)
  const filteredPods = useMemo(() => SAMPLE_CLUSTER.pods.filter((pod) => (
    `${pod.name} ${pod.namespace} ${pod.node}`.toLowerCase().includes(search.toLowerCase())
    && (namespace === 'All namespaces' || pod.namespace === namespace)
  )), [search, namespace])

  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-accent-cyan">Orchestration</p><h1 className="mt-1 text-2xl font-semibold text-orbitra-text">Kubernetes</h1><p className="mt-2 text-sm text-orbitra-muted">Explore an illustrative cluster, its nodes, pods, and namespaces.</p></div><Badge tone="orange">Mock cluster · not connected</Badge></header>
    <Card className="flex flex-wrap items-center justify-between gap-4 p-4 sm:p-5"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent-purple/15 text-accent-purple"><Boxes size={20}/></span><div><h2 className="font-semibold text-orbitra-text">{SAMPLE_CLUSTER.name}</h2><p className="mt-1 text-xs text-orbitra-muted">{SAMPLE_CLUSTER.provider} · {SAMPLE_CLUSTER.region} · {SAMPLE_CLUSTER.version}</p></div></div><div className="flex items-center gap-2 text-sm text-accent-green"><ShieldCheck size={17}/> Sample control plane healthy</div></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Server} label="Nodes" value={SAMPLE_CLUSTER.nodes.length} note="All sample nodes ready"/><Stat icon={Boxes} label="Pods" value={SAMPLE_CLUSTER.pods.length} note="Across 3 namespaces"/><Stat icon={Layers3} label="Namespaces" value={SAMPLE_CLUSTER.namespaces.length} note="4 active namespaces"/><Stat icon={Cpu} label="Cluster CPU" value={`${Math.round(SAMPLE_CLUSTER.nodes.reduce((sum, node) => sum + node.cpu, 0) / SAMPLE_CLUSTER.nodes.length)}%`} note="Sample average usage"/></div>
    <div className="flex flex-wrap gap-2 border-b border-orbitra-border pb-3" role="tablist" aria-label="Kubernetes cluster sections">{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`rounded-lg px-3 py-2 text-sm transition-colors ${tab === item ? 'bg-accent-blue/15 text-accent-cyan' : 'text-orbitra-muted hover:bg-orbitra-800 hover:text-orbitra-text'}`}>{item}</button>)}</div>
    {(tab === 'Overview' || tab === 'Nodes') && <Card title={tab === 'Overview' ? 'Cluster nodes' : 'Nodes'} description="Node readiness and sample resource utilization."><div className="grid gap-3 lg:grid-cols-3">{SAMPLE_CLUSTER.nodes.map((node) => <button key={node.name} onClick={() => setSelected({ type: 'Node', ...node })} className="rounded-xl border border-orbitra-border bg-orbitra-900/50 p-4 text-left transition-colors hover:border-orbitra-600"><div className="flex items-start justify-between"><div><h3 className="font-medium text-orbitra-text">{node.name}</h3><p className="mt-1 text-xs text-orbitra-muted">{node.zone} · {node.pods} pods</p></div><Badge tone="success">{node.status}</Badge></div><div className="mt-4 space-y-3"><Meter icon={Cpu} label="CPU" value={node.cpu}/><Meter icon={MemoryStick} label="Memory" value={node.memory}/></div></button>)}</div></Card>}
      {(tab === 'Overview' || tab === 'Pods') && <Card title="Pods" description="Pod states are illustrative and are not fetched from Kubernetes."><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_12rem]"><label className="relative"><span className="sr-only">Search pods</span><Search size={16} className="absolute top-1/2 left-3 -translate-y-1/2 text-orbitra-muted"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search pod, node, namespace..." className="w-full rounded-lg border border-orbitra-border bg-orbitra-900 py-2.5 pr-3 pl-9 text-sm text-orbitra-text outline-none focus:ring-2 focus:ring-accent-blue/70"/></label><select aria-label="Filter pods by namespace" value={namespace} onChange={(event) => setNamespace(event.target.value)} className="rounded-lg border border-orbitra-border bg-orbitra-900 px-3 py-2.5 text-sm text-orbitra-text"><option>All namespaces</option>{SAMPLE_CLUSTER.namespaces.map((item) => <option key={item.name}>{item.name}</option>)}</select></div>{filteredPods.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><caption className="sr-only">Illustrative Kubernetes pods</caption><thead><tr className="border-b border-orbitra-border text-xs uppercase tracking-wide text-orbitra-muted">{['Pod', 'Namespace', 'Status', 'Restarts', 'Node', 'Age'].map((label) => <th key={label} scope="col" className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-orbitra-border">{filteredPods.map((pod) => <tr key={pod.name} className="hover:bg-orbitra-800/40"><th scope="row" className="px-3 py-3 font-mono text-xs font-medium"><button type="button" onClick={() => setSelected({ type: 'Pod', ...pod })} className="rounded text-left text-orbitra-text hover:text-accent-cyan focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent-cyan">{pod.name}</button></th><td className="px-3 py-3 text-orbitra-muted">{pod.namespace}</td><td className="px-3 py-3"><Badge tone={podTone[pod.status] || 'gray'}>{pod.status}</Badge></td><td className="px-3 py-3 text-orbitra-muted">{pod.restarts}</td><td className="px-3 py-3 text-orbitra-muted">{pod.node}</td><td className="px-3 py-3 text-orbitra-muted">{pod.age}</td></tr>)}</tbody></table></div> : <EmptyState title="No pods match" description="Try another pod name or namespace."/>}</Card>}
    {(tab === 'Overview' || tab === 'Namespaces') && <Card title="Namespaces" description="Sample namespace inventory and workload counts."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{SAMPLE_CLUSTER.namespaces.map((item) => <button key={item.name} onClick={() => { setNamespace(item.name); setTab('Pods') }} className="rounded-xl border border-orbitra-border bg-orbitra-900/50 p-4 text-left hover:border-orbitra-600"><div className="flex items-center justify-between"><h3 className="font-medium text-orbitra-text">{item.name}</h3><Badge tone="green">{item.status}</Badge></div><p className="mt-3 text-xs text-orbitra-muted">{item.workloads} workloads · {item.pods} listed pods</p></button>)}</div></Card>}
    <p className="text-xs text-orbitra-muted">Cluster, node, pod, and namespace details are sample data. This page does not connect to or modify a Kubernetes cluster.</p>
    <Modal open={Boolean(selected)} title={selected ? `${selected.type} details` : 'Details'} onClose={() => setSelected(null)}><h3 className="break-all font-medium text-orbitra-text">{selected?.name}</h3><dl className="mt-4 grid grid-cols-2 gap-3">{Object.entries(selected || {}).filter(([key]) => !['type', 'name'].includes(key)).map(([key, value]) => <div key={key} className="rounded-lg border border-orbitra-border bg-orbitra-900/50 p-3"><dt className="text-xs capitalize text-orbitra-muted">{key}</dt><dd className="mt-1 break-words text-sm text-orbitra-text">{String(value)}</dd></div>)}</dl><p className="mt-4 text-xs text-orbitra-muted">Sample detail panel. No cluster API request was made.</p></Modal>
  </div>
}

function Stat({ icon: Icon, label, value, note }) { return <Card className="p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent-blue/15 text-accent-cyan"><Icon size={17}/></span><div><p className="text-xs text-orbitra-muted">{label}</p><p className="mt-0.5 text-xl font-semibold text-orbitra-text">{value}</p></div></div><p className="mt-3 text-xs text-orbitra-muted">{note}</p></Card> }
function Meter({ icon: Icon, label, value }) { return <div className="flex items-center gap-2 text-xs text-orbitra-muted"><Icon size={13}/><span className="w-12">{label}</span><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-orbitra-700"><div className={`h-full rounded-full ${value > 80 ? 'bg-accent-orange' : 'bg-accent-cyan'}`} style={{ width: `${value}%` }}/></div><span className="w-9 text-right">{value}%</span></div> }
export default KubernetesPage
